spring.application.name=RegisterLogin
spring.datasource.url=jdbc:postgresql://localhost:5432/docflow
spring.datasource.username=docflow_user
spring.datasource.password=docflow_pass
spring.jpa.hibernate.ddl-auto=update